#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('test.db')
print("Opened database successfully");

conn.execute("INSERT INTO COMPANY (ID,NAME,WRITER,GENRE,LOGLINE,SALARY,) \
      VALUES (1, 'Paul', 'Mark', 'Horror', 'Log', 50, )");


conn.commit()
print("Records created successfully");
conn.close()
