#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('test.db')
print("Opened database successfully");

conn.execute("INSERT INTO COMPANY (ID, NAME, WRITER,GENRE,  ) \
      VALUES (1, 'Paul', 'Mark', 'Horror',)");


conn.commit()
print("Records created successfully");
conn.close()
