#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('test.db')

print("Opened database") 

conn.execute('''CREATE TABLE COMPANY
         (ID INT PRIMARY KEY     NOT NULL,
         NAME           TEXT    NOT NULL,
         WRITER         TEXT    NOT NULL,
         GENRE          TEXT    NOT NULL,
         LOGLINE        TEXT    NOT NULL,
         AGE            INT     NOT NULL,
         ADDRESS        CHAR(50),
         SALARY         REAL);''')
print("Table created successfully");

conn.close()
